# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.example.com:12051
      - CORE_PEER_LOCALMSPID=Org3MSP
    extra_hosts:
        - "orderer.example.com:146.164.69.198"
        - "orderer2.example.com:146.164.69.198"
        - "orderer3.example.com:146.164.69.198"
        - "orderer4.example.com:146.164.69.198"
        - "orderer5.example.com:146.164.69.198"
        - "ca_peerOrg1:146.164.69.198"
        - "ca_peerOrg2:146.164.69.198"
        - "ca_peerOrg3:146.164.69.198"
        - "ca_peerOrg4:146.164.69.198"
        - "ca_peerOrg5:146.164.69.198"
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.example.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.org3.example.com:
    container_name: peer1.org3.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.example.com
      - CORE_PEER_ADDRESS=peer1.org3.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
    extra_hosts:
        - "orderer.example.com:146.164.69.198"
        - "orderer2.example.com:146.164.69.198"
        - "orderer3.example.com:146.164.69.198"
        - "orderer4.example.com:146.164.69.198"
        - "orderer5.example.com:146.164.69.198"
        - "ca_peerOrg1:146.164.69.198"
        - "ca_peerOrg2:146.164.69.198"
        - "ca_peerOrg3:146.164.69.198"
        - "ca_peerOrg4:146.164.69.198"
        - "ca_peerOrg5:146.164.69.198"
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org3.example.com:/var/hyperledger/production
    ports:
      - 12051:12051
